// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class Clip {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Clip {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsClip(bb:flatbuffers.ByteBuffer, obj?:Clip):Clip {
  return (obj || new Clip()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsClip(bb:flatbuffers.ByteBuffer, obj?:Clip):Clip {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Clip()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

clipId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

count():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

framesPerSecond():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

width():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

height():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

audioId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startClip(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addClipId(builder:flatbuffers.Builder, clipId:bigint) {
  builder.addFieldInt64(0, clipId, BigInt('0'));
}

static addCount(builder:flatbuffers.Builder, count:number) {
  builder.addFieldInt32(1, count, 0);
}

static addFramesPerSecond(builder:flatbuffers.Builder, framesPerSecond:number) {
  builder.addFieldFloat64(2, framesPerSecond, 0.0);
}

static addWidth(builder:flatbuffers.Builder, width:number) {
  builder.addFieldInt32(3, width, 0);
}

static addHeight(builder:flatbuffers.Builder, height:number) {
  builder.addFieldInt32(4, height, 0);
}

static addAudioId(builder:flatbuffers.Builder, audioId:bigint) {
  builder.addFieldInt64(5, audioId, BigInt('0'));
}

static endClip(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishClipBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedClipBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createClip(builder:flatbuffers.Builder, clipId:bigint, count:number, framesPerSecond:number, width:number, height:number, audioId:bigint):flatbuffers.Offset {
  Clip.startClip(builder);
  Clip.addClipId(builder, clipId);
  Clip.addCount(builder, count);
  Clip.addFramesPerSecond(builder, framesPerSecond);
  Clip.addWidth(builder, width);
  Clip.addHeight(builder, height);
  Clip.addAudioId(builder, audioId);
  return Clip.endClip(builder);
}
}
