// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum CompressionMethod {
  Disabled = 0,
  H264 = 1,
  H265 = 2,
  Jpeg = 3
}
