// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GenerationEstimation {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GenerationEstimation {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGenerationEstimation(bb:flatbuffers.ByteBuffer, obj?:GenerationEstimation):GenerationEstimation {
  return (obj || new GenerationEstimation()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGenerationEstimation(bb:flatbuffers.ByteBuffer, obj?:GenerationEstimation):GenerationEstimation {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GenerationEstimation()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

textEncoded():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

imageEncoded():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

samplingStep():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

imageDecoded():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

secondPassImageEncoded():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

secondPassSamplingStep():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

secondPassImageDecoded():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

imageUpscaled():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

faceRestored():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startGenerationEstimation(builder:flatbuffers.Builder) {
  builder.startObject(9);
}

static addTextEncoded(builder:flatbuffers.Builder, textEncoded:number) {
  builder.addFieldFloat32(0, textEncoded, 0.0);
}

static addImageEncoded(builder:flatbuffers.Builder, imageEncoded:number) {
  builder.addFieldFloat32(1, imageEncoded, 0.0);
}

static addSamplingStep(builder:flatbuffers.Builder, samplingStep:number) {
  builder.addFieldFloat32(2, samplingStep, 0.0);
}

static addImageDecoded(builder:flatbuffers.Builder, imageDecoded:number) {
  builder.addFieldFloat32(3, imageDecoded, 0.0);
}

static addSecondPassImageEncoded(builder:flatbuffers.Builder, secondPassImageEncoded:number) {
  builder.addFieldFloat32(4, secondPassImageEncoded, 0.0);
}

static addSecondPassSamplingStep(builder:flatbuffers.Builder, secondPassSamplingStep:number) {
  builder.addFieldFloat32(5, secondPassSamplingStep, 0.0);
}

static addSecondPassImageDecoded(builder:flatbuffers.Builder, secondPassImageDecoded:number) {
  builder.addFieldFloat32(6, secondPassImageDecoded, 0.0);
}

static addImageUpscaled(builder:flatbuffers.Builder, imageUpscaled:number) {
  builder.addFieldFloat32(7, imageUpscaled, 0.0);
}

static addFaceRestored(builder:flatbuffers.Builder, faceRestored:number) {
  builder.addFieldFloat32(8, faceRestored, 0.0);
}

static endGenerationEstimation(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGenerationEstimation(builder:flatbuffers.Builder, textEncoded:number, imageEncoded:number, samplingStep:number, imageDecoded:number, secondPassImageEncoded:number, secondPassSamplingStep:number, secondPassImageDecoded:number, imageUpscaled:number, faceRestored:number):flatbuffers.Offset {
  GenerationEstimation.startGenerationEstimation(builder);
  GenerationEstimation.addTextEncoded(builder, textEncoded);
  GenerationEstimation.addImageEncoded(builder, imageEncoded);
  GenerationEstimation.addSamplingStep(builder, samplingStep);
  GenerationEstimation.addImageDecoded(builder, imageDecoded);
  GenerationEstimation.addSecondPassImageEncoded(builder, secondPassImageEncoded);
  GenerationEstimation.addSecondPassSamplingStep(builder, secondPassSamplingStep);
  GenerationEstimation.addSecondPassImageDecoded(builder, secondPassImageDecoded);
  GenerationEstimation.addImageUpscaled(builder, imageUpscaled);
  GenerationEstimation.addFaceRestored(builder, faceRestored);
  return GenerationEstimation.endGenerationEstimation(builder);
}
}
