// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum LoRATrainableLayer {
  LatentsEmbedder = 0,
  ContextEmbedder = 1,
  ProjectOut = 2,
  Qkv = 3,
  QkvContext = 4,
  Out = 5,
  OutContext = 6,
  FeedForward = 7,
  FeedForwardContext = 8
}
