// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { LoRAMode } from './lo-ramode.js';


export class LoRA {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LoRA {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLoRA(bb:flatbuffers.ByteBuffer, obj?:LoRA):LoRA {
  return (obj || new LoRA()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLoRA(bb:flatbuffers.ByteBuffer, obj?:LoRA):LoRA {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LoRA()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

file():string|null
file(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
file(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

weight():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.6;
}

mode():LoRAMode {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : LoRAMode.All;
}

static startLoRA(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addFile(builder:flatbuffers.Builder, fileOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, fileOffset, 0);
}

static addWeight(builder:flatbuffers.Builder, weight:number) {
  builder.addFieldFloat32(1, weight, 0.6);
}

static addMode(builder:flatbuffers.Builder, mode:LoRAMode) {
  builder.addFieldInt8(2, mode, LoRAMode.All);
}

static endLoRA(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createLoRA(builder:flatbuffers.Builder, fileOffset:flatbuffers.Offset, weight:number, mode:LoRAMode):flatbuffers.Offset {
  LoRA.startLoRA(builder);
  LoRA.addFile(builder, fileOffset);
  LoRA.addWeight(builder, weight);
  LoRA.addMode(builder, mode);
  return LoRA.endLoRA(builder);
}
}
