// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { LoRATrainableLayer } from './lo-ratrainable-layer.js';


export class LoRATrainingConfiguration {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LoRATrainingConfiguration {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLoRATrainingConfiguration(bb:flatbuffers.ByteBuffer, obj?:LoRATrainingConfiguration):LoRATrainingConfiguration {
  return (obj || new LoRATrainingConfiguration()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLoRATrainingConfiguration(bb:flatbuffers.ByteBuffer, obj?:LoRATrainingConfiguration):LoRATrainingConfiguration {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LoRATrainingConfiguration()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

startWidth():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

startHeight():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

seed():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

trainingSteps():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

baseModel():string|null
baseModel(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
baseModel(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

networkDim():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

networkScale():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

unetLearningRate():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

saveEveryNSteps():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

warmupSteps():number {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

gradientAccumulationSteps():number {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

cotrainTextModel():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

textModelLearningRate():number {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

clipSkip():number {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 1;
}

noiseOffset():number {
  const offset = this.bb!.__offset(this.bb_pos, 36);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

denoisingStart():number {
  const offset = this.bb!.__offset(this.bb_pos, 38);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

denoisingEnd():number {
  const offset = this.bb!.__offset(this.bb_pos, 40);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

triggerWord():string|null
triggerWord(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
triggerWord(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 42);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

autoFillPrompt():string|null
autoFillPrompt(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
autoFillPrompt(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 44);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

autoCaptioning():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 46);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

cotrainCustomEmbedding():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 48);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

customEmbeddingLearningRate():number {
  const offset = this.bb!.__offset(this.bb_pos, 50);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.05;
}

customEmbeddingLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 52);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 4;
}

stopEmbeddingTrainingAtStep():number {
  const offset = this.bb!.__offset(this.bb_pos, 54);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 500;
}

trainableLayers(index: number):LoRATrainableLayer|null {
  const offset = this.bb!.__offset(this.bb_pos, 56);
  return offset ? this.bb!.readInt8(this.bb!.__vector(this.bb_pos + offset) + index) : null;
}

trainableLayersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 56);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

trainableLayersArray():Int8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 56);
  return offset ? new Int8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

layerIndices(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 58);
  return offset ? this.bb!.readUint32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

layerIndicesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 58);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

layerIndicesArray():Uint32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 58);
  return offset ? new Uint32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

shift():number {
  const offset = this.bb!.__offset(this.bb_pos, 60);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 1.0;
}

resolutionDependentShift():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 62);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

guidanceEmbedLowerBound():number {
  const offset = this.bb!.__offset(this.bb_pos, 64);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 3.0;
}

guidanceEmbedUpperBound():number {
  const offset = this.bb!.__offset(this.bb_pos, 66);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 4.0;
}

unetLearningRateLowerBound():number {
  const offset = this.bb!.__offset(this.bb_pos, 68);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

stepsBetweenRestarts():number {
  const offset = this.bb!.__offset(this.bb_pos, 70);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 200;
}

captionDropoutRate():number {
  const offset = this.bb!.__offset(this.bb_pos, 72);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

orthonormalLoraDown():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 74);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

maxTextLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 76);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 512;
}

useImageAspectRatio():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 78);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

additionalScales(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 80);
  return offset ? this.bb!.readUint16(this.bb!.__vector(this.bb_pos + offset) + index * 2) : 0;
}

additionalScalesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 80);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

additionalScalesArray():Uint16Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 80);
  return offset ? new Uint16Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

powerEmaLowerBound():number {
  const offset = this.bb!.__offset(this.bb_pos, 82);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

powerEmaUpperBound():number {
  const offset = this.bb!.__offset(this.bb_pos, 84);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startLoRATrainingConfiguration(builder:flatbuffers.Builder) {
  builder.startObject(41);
}

static addId(builder:flatbuffers.Builder, id:bigint) {
  builder.addFieldInt64(0, id, BigInt('0'));
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static addStartWidth(builder:flatbuffers.Builder, startWidth:number) {
  builder.addFieldInt16(2, startWidth, 0);
}

static addStartHeight(builder:flatbuffers.Builder, startHeight:number) {
  builder.addFieldInt16(3, startHeight, 0);
}

static addSeed(builder:flatbuffers.Builder, seed:number) {
  builder.addFieldInt32(4, seed, 0);
}

static addTrainingSteps(builder:flatbuffers.Builder, trainingSteps:number) {
  builder.addFieldInt32(5, trainingSteps, 0);
}

static addBaseModel(builder:flatbuffers.Builder, baseModelOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, baseModelOffset, 0);
}

static addNetworkDim(builder:flatbuffers.Builder, networkDim:number) {
  builder.addFieldInt16(7, networkDim, 0);
}

static addNetworkScale(builder:flatbuffers.Builder, networkScale:number) {
  builder.addFieldFloat32(8, networkScale, 0.0);
}

static addUnetLearningRate(builder:flatbuffers.Builder, unetLearningRate:number) {
  builder.addFieldFloat32(9, unetLearningRate, 0.0);
}

static addSaveEveryNSteps(builder:flatbuffers.Builder, saveEveryNSteps:number) {
  builder.addFieldInt32(10, saveEveryNSteps, 0);
}

static addWarmupSteps(builder:flatbuffers.Builder, warmupSteps:number) {
  builder.addFieldInt32(11, warmupSteps, 0);
}

static addGradientAccumulationSteps(builder:flatbuffers.Builder, gradientAccumulationSteps:number) {
  builder.addFieldInt32(12, gradientAccumulationSteps, 0);
}

static addCotrainTextModel(builder:flatbuffers.Builder, cotrainTextModel:boolean) {
  builder.addFieldInt8(13, +cotrainTextModel, +false);
}

static addTextModelLearningRate(builder:flatbuffers.Builder, textModelLearningRate:number) {
  builder.addFieldFloat32(14, textModelLearningRate, 0.0);
}

static addClipSkip(builder:flatbuffers.Builder, clipSkip:number) {
  builder.addFieldInt32(15, clipSkip, 1);
}

static addNoiseOffset(builder:flatbuffers.Builder, noiseOffset:number) {
  builder.addFieldFloat32(16, noiseOffset, 0.0);
}

static addDenoisingStart(builder:flatbuffers.Builder, denoisingStart:number) {
  builder.addFieldFloat32(17, denoisingStart, 0.0);
}

static addDenoisingEnd(builder:flatbuffers.Builder, denoisingEnd:number) {
  builder.addFieldFloat32(18, denoisingEnd, 0.0);
}

static addTriggerWord(builder:flatbuffers.Builder, triggerWordOffset:flatbuffers.Offset) {
  builder.addFieldOffset(19, triggerWordOffset, 0);
}

static addAutoFillPrompt(builder:flatbuffers.Builder, autoFillPromptOffset:flatbuffers.Offset) {
  builder.addFieldOffset(20, autoFillPromptOffset, 0);
}

static addAutoCaptioning(builder:flatbuffers.Builder, autoCaptioning:boolean) {
  builder.addFieldInt8(21, +autoCaptioning, +false);
}

static addCotrainCustomEmbedding(builder:flatbuffers.Builder, cotrainCustomEmbedding:boolean) {
  builder.addFieldInt8(22, +cotrainCustomEmbedding, +false);
}

static addCustomEmbeddingLearningRate(builder:flatbuffers.Builder, customEmbeddingLearningRate:number) {
  builder.addFieldFloat32(23, customEmbeddingLearningRate, 0.05);
}

static addCustomEmbeddingLength(builder:flatbuffers.Builder, customEmbeddingLength:number) {
  builder.addFieldInt32(24, customEmbeddingLength, 4);
}

static addStopEmbeddingTrainingAtStep(builder:flatbuffers.Builder, stopEmbeddingTrainingAtStep:number) {
  builder.addFieldInt32(25, stopEmbeddingTrainingAtStep, 500);
}

static addTrainableLayers(builder:flatbuffers.Builder, trainableLayersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(26, trainableLayersOffset, 0);
}

static createTrainableLayersVector(builder:flatbuffers.Builder, data:LoRATrainableLayer[]):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startTrainableLayersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addLayerIndices(builder:flatbuffers.Builder, layerIndicesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(27, layerIndicesOffset, 0);
}

static createLayerIndicesVector(builder:flatbuffers.Builder, data:number[]|Uint32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createLayerIndicesVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createLayerIndicesVector(builder:flatbuffers.Builder, data:number[]|Uint32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]!);
  }
  return builder.endVector();
}

static startLayerIndicesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addShift(builder:flatbuffers.Builder, shift:number) {
  builder.addFieldFloat32(28, shift, 1.0);
}

static addResolutionDependentShift(builder:flatbuffers.Builder, resolutionDependentShift:boolean) {
  builder.addFieldInt8(29, +resolutionDependentShift, +false);
}

static addGuidanceEmbedLowerBound(builder:flatbuffers.Builder, guidanceEmbedLowerBound:number) {
  builder.addFieldFloat32(30, guidanceEmbedLowerBound, 3.0);
}

static addGuidanceEmbedUpperBound(builder:flatbuffers.Builder, guidanceEmbedUpperBound:number) {
  builder.addFieldFloat32(31, guidanceEmbedUpperBound, 4.0);
}

static addUnetLearningRateLowerBound(builder:flatbuffers.Builder, unetLearningRateLowerBound:number) {
  builder.addFieldFloat32(32, unetLearningRateLowerBound, 0.0);
}

static addStepsBetweenRestarts(builder:flatbuffers.Builder, stepsBetweenRestarts:number) {
  builder.addFieldInt32(33, stepsBetweenRestarts, 200);
}

static addCaptionDropoutRate(builder:flatbuffers.Builder, captionDropoutRate:number) {
  builder.addFieldFloat32(34, captionDropoutRate, 0.0);
}

static addOrthonormalLoraDown(builder:flatbuffers.Builder, orthonormalLoraDown:boolean) {
  builder.addFieldInt8(35, +orthonormalLoraDown, +false);
}

static addMaxTextLength(builder:flatbuffers.Builder, maxTextLength:number) {
  builder.addFieldInt32(36, maxTextLength, 512);
}

static addUseImageAspectRatio(builder:flatbuffers.Builder, useImageAspectRatio:boolean) {
  builder.addFieldInt8(37, +useImageAspectRatio, +false);
}

static addAdditionalScales(builder:flatbuffers.Builder, additionalScalesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(38, additionalScalesOffset, 0);
}

static createAdditionalScalesVector(builder:flatbuffers.Builder, data:number[]|Uint16Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createAdditionalScalesVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createAdditionalScalesVector(builder:flatbuffers.Builder, data:number[]|Uint16Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(2, data.length, 2);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt16(data[i]!);
  }
  return builder.endVector();
}

static startAdditionalScalesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(2, numElems, 2);
}

static addPowerEmaLowerBound(builder:flatbuffers.Builder, powerEmaLowerBound:number) {
  builder.addFieldFloat32(39, powerEmaLowerBound, 0.0);
}

static addPowerEmaUpperBound(builder:flatbuffers.Builder, powerEmaUpperBound:number) {
  builder.addFieldFloat32(40, powerEmaUpperBound, 0.0);
}

static endLoRATrainingConfiguration(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishLoRATrainingConfigurationBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedLoRATrainingConfigurationBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createLoRATrainingConfiguration(builder:flatbuffers.Builder, id:bigint, nameOffset:flatbuffers.Offset, startWidth:number, startHeight:number, seed:number, trainingSteps:number, baseModelOffset:flatbuffers.Offset, networkDim:number, networkScale:number, unetLearningRate:number, saveEveryNSteps:number, warmupSteps:number, gradientAccumulationSteps:number, cotrainTextModel:boolean, textModelLearningRate:number, clipSkip:number, noiseOffset:number, denoisingStart:number, denoisingEnd:number, triggerWordOffset:flatbuffers.Offset, autoFillPromptOffset:flatbuffers.Offset, autoCaptioning:boolean, cotrainCustomEmbedding:boolean, customEmbeddingLearningRate:number, customEmbeddingLength:number, stopEmbeddingTrainingAtStep:number, trainableLayersOffset:flatbuffers.Offset, layerIndicesOffset:flatbuffers.Offset, shift:number, resolutionDependentShift:boolean, guidanceEmbedLowerBound:number, guidanceEmbedUpperBound:number, unetLearningRateLowerBound:number, stepsBetweenRestarts:number, captionDropoutRate:number, orthonormalLoraDown:boolean, maxTextLength:number, useImageAspectRatio:boolean, additionalScalesOffset:flatbuffers.Offset, powerEmaLowerBound:number, powerEmaUpperBound:number):flatbuffers.Offset {
  LoRATrainingConfiguration.startLoRATrainingConfiguration(builder);
  LoRATrainingConfiguration.addId(builder, id);
  LoRATrainingConfiguration.addName(builder, nameOffset);
  LoRATrainingConfiguration.addStartWidth(builder, startWidth);
  LoRATrainingConfiguration.addStartHeight(builder, startHeight);
  LoRATrainingConfiguration.addSeed(builder, seed);
  LoRATrainingConfiguration.addTrainingSteps(builder, trainingSteps);
  LoRATrainingConfiguration.addBaseModel(builder, baseModelOffset);
  LoRATrainingConfiguration.addNetworkDim(builder, networkDim);
  LoRATrainingConfiguration.addNetworkScale(builder, networkScale);
  LoRATrainingConfiguration.addUnetLearningRate(builder, unetLearningRate);
  LoRATrainingConfiguration.addSaveEveryNSteps(builder, saveEveryNSteps);
  LoRATrainingConfiguration.addWarmupSteps(builder, warmupSteps);
  LoRATrainingConfiguration.addGradientAccumulationSteps(builder, gradientAccumulationSteps);
  LoRATrainingConfiguration.addCotrainTextModel(builder, cotrainTextModel);
  LoRATrainingConfiguration.addTextModelLearningRate(builder, textModelLearningRate);
  LoRATrainingConfiguration.addClipSkip(builder, clipSkip);
  LoRATrainingConfiguration.addNoiseOffset(builder, noiseOffset);
  LoRATrainingConfiguration.addDenoisingStart(builder, denoisingStart);
  LoRATrainingConfiguration.addDenoisingEnd(builder, denoisingEnd);
  LoRATrainingConfiguration.addTriggerWord(builder, triggerWordOffset);
  LoRATrainingConfiguration.addAutoFillPrompt(builder, autoFillPromptOffset);
  LoRATrainingConfiguration.addAutoCaptioning(builder, autoCaptioning);
  LoRATrainingConfiguration.addCotrainCustomEmbedding(builder, cotrainCustomEmbedding);
  LoRATrainingConfiguration.addCustomEmbeddingLearningRate(builder, customEmbeddingLearningRate);
  LoRATrainingConfiguration.addCustomEmbeddingLength(builder, customEmbeddingLength);
  LoRATrainingConfiguration.addStopEmbeddingTrainingAtStep(builder, stopEmbeddingTrainingAtStep);
  LoRATrainingConfiguration.addTrainableLayers(builder, trainableLayersOffset);
  LoRATrainingConfiguration.addLayerIndices(builder, layerIndicesOffset);
  LoRATrainingConfiguration.addShift(builder, shift);
  LoRATrainingConfiguration.addResolutionDependentShift(builder, resolutionDependentShift);
  LoRATrainingConfiguration.addGuidanceEmbedLowerBound(builder, guidanceEmbedLowerBound);
  LoRATrainingConfiguration.addGuidanceEmbedUpperBound(builder, guidanceEmbedUpperBound);
  LoRATrainingConfiguration.addUnetLearningRateLowerBound(builder, unetLearningRateLowerBound);
  LoRATrainingConfiguration.addStepsBetweenRestarts(builder, stepsBetweenRestarts);
  LoRATrainingConfiguration.addCaptionDropoutRate(builder, captionDropoutRate);
  LoRATrainingConfiguration.addOrthonormalLoraDown(builder, orthonormalLoraDown);
  LoRATrainingConfiguration.addMaxTextLength(builder, maxTextLength);
  LoRATrainingConfiguration.addUseImageAspectRatio(builder, useImageAspectRatio);
  LoRATrainingConfiguration.addAdditionalScales(builder, additionalScalesOffset);
  LoRATrainingConfiguration.addPowerEmaLowerBound(builder, powerEmaLowerBound);
  LoRATrainingConfiguration.addPowerEmaUpperBound(builder, powerEmaUpperBound);
  return LoRATrainingConfiguration.endLoRATrainingConfiguration(builder);
}
}
