// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ModelMixingItem } from './model-mixing-item.js';
import { ModelMixingLoRA } from './model-mixing-lo-ra.js';
import { ModelMixingMode } from './model-mixing-mode.js';


export class ModelMixingMetadata {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ModelMixingMetadata {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsModelMixingMetadata(bb:flatbuffers.ByteBuffer, obj?:ModelMixingMetadata):ModelMixingMetadata {
  return (obj || new ModelMixingMetadata()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsModelMixingMetadata(bb:flatbuffers.ByteBuffer, obj?:ModelMixingMetadata):ModelMixingMetadata {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ModelMixingMetadata()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

triggerWord():string|null
triggerWord(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
triggerWord(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

vPrediction():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

upcastAttention():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

mode():ModelMixingMode {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ModelMixingMode.WeightedSum;
}

items(index: number, obj?:ModelMixingItem):ModelMixingItem|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new ModelMixingItem()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

itemsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

note():string|null
note(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
note(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

encoder():string|null
encoder(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
encoder(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

decoder():string|null
decoder(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
decoder(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

loras(index: number, obj?:ModelMixingLoRA):ModelMixingLoRA|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? (obj || new ModelMixingLoRA()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

lorasLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startModelMixingMetadata(builder:flatbuffers.Builder) {
  builder.startObject(10);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static addTriggerWord(builder:flatbuffers.Builder, triggerWordOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, triggerWordOffset, 0);
}

static addVPrediction(builder:flatbuffers.Builder, vPrediction:boolean) {
  builder.addFieldInt8(2, +vPrediction, +false);
}

static addUpcastAttention(builder:flatbuffers.Builder, upcastAttention:boolean) {
  builder.addFieldInt8(3, +upcastAttention, +false);
}

static addMode(builder:flatbuffers.Builder, mode:ModelMixingMode) {
  builder.addFieldInt8(4, mode, ModelMixingMode.WeightedSum);
}

static addItems(builder:flatbuffers.Builder, itemsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, itemsOffset, 0);
}

static createItemsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startItemsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addNote(builder:flatbuffers.Builder, noteOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, noteOffset, 0);
}

static addEncoder(builder:flatbuffers.Builder, encoderOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, encoderOffset, 0);
}

static addDecoder(builder:flatbuffers.Builder, decoderOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, decoderOffset, 0);
}

static addLoras(builder:flatbuffers.Builder, lorasOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, lorasOffset, 0);
}

static createLorasVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startLorasVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endModelMixingMetadata(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishModelMixingMetadataBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedModelMixingMetadataBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createModelMixingMetadata(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, triggerWordOffset:flatbuffers.Offset, vPrediction:boolean, upcastAttention:boolean, mode:ModelMixingMode, itemsOffset:flatbuffers.Offset, noteOffset:flatbuffers.Offset, encoderOffset:flatbuffers.Offset, decoderOffset:flatbuffers.Offset, lorasOffset:flatbuffers.Offset):flatbuffers.Offset {
  ModelMixingMetadata.startModelMixingMetadata(builder);
  ModelMixingMetadata.addName(builder, nameOffset);
  ModelMixingMetadata.addTriggerWord(builder, triggerWordOffset);
  ModelMixingMetadata.addVPrediction(builder, vPrediction);
  ModelMixingMetadata.addUpcastAttention(builder, upcastAttention);
  ModelMixingMetadata.addMode(builder, mode);
  ModelMixingMetadata.addItems(builder, itemsOffset);
  ModelMixingMetadata.addNote(builder, noteOffset);
  ModelMixingMetadata.addEncoder(builder, encoderOffset);
  ModelMixingMetadata.addDecoder(builder, decoderOffset);
  ModelMixingMetadata.addLoras(builder, lorasOffset);
  return ModelMixingMetadata.endModelMixingMetadata(builder);
}
}
