// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ModelMixingLoRA {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ModelMixingLoRA {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsModelMixingLoRA(bb:flatbuffers.ByteBuffer, obj?:ModelMixingLoRA):ModelMixingLoRA {
  return (obj || new ModelMixingLoRA()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsModelMixingLoRA(bb:flatbuffers.ByteBuffer, obj?:ModelMixingLoRA):ModelMixingLoRA {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ModelMixingLoRA()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

file():string|null
file(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
file(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

weight():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.6;
}

static startModelMixingLoRA(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addFile(builder:flatbuffers.Builder, fileOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, fileOffset, 0);
}

static addWeight(builder:flatbuffers.Builder, weight:number) {
  builder.addFieldFloat32(1, weight, 0.6);
}

static endModelMixingLoRA(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createModelMixingLoRA(builder:flatbuffers.Builder, fileOffset:flatbuffers.Offset, weight:number):flatbuffers.Offset {
  ModelMixingLoRA.startModelMixingLoRA(builder);
  ModelMixingLoRA.addFile(builder, fileOffset);
  ModelMixingLoRA.addWeight(builder, weight);
  return ModelMixingLoRA.endModelMixingLoRA(builder);
}
}
