// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class PaintColor {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PaintColor {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPaintColor(bb:flatbuffers.ByteBuffer, obj?:PaintColor):PaintColor {
  return (obj || new PaintColor()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPaintColor(bb:flatbuffers.ByteBuffer, obj?:PaintColor):PaintColor {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PaintColor()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

index():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

r():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

g():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

b():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

a():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startPaintColor(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addIndex(builder:flatbuffers.Builder, index:bigint) {
  builder.addFieldInt64(0, index, BigInt('0'));
}

static addR(builder:flatbuffers.Builder, r:number) {
  builder.addFieldFloat32(1, r, 0.0);
}

static addG(builder:flatbuffers.Builder, g:number) {
  builder.addFieldFloat32(2, g, 0.0);
}

static addB(builder:flatbuffers.Builder, b:number) {
  builder.addFieldFloat32(3, b, 0.0);
}

static addA(builder:flatbuffers.Builder, a:number) {
  builder.addFieldFloat32(4, a, 0.0);
}

static endPaintColor(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishPaintColorBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedPaintColorBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createPaintColor(builder:flatbuffers.Builder, index:bigint, r:number, g:number, b:number, a:number):flatbuffers.Offset {
  PaintColor.startPaintColor(builder);
  PaintColor.addIndex(builder, index);
  PaintColor.addR(builder, r);
  PaintColor.addG(builder, g);
  PaintColor.addB(builder, b);
  PaintColor.addA(builder, a);
  return PaintColor.endPaintColor(builder);
}
}
