// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class PeerConnectionId {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PeerConnectionId {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPeerConnectionId(bb:flatbuffers.ByteBuffer, obj?:PeerConnectionId):PeerConnectionId {
  return (obj || new PeerConnectionId()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPeerConnectionId(bb:flatbuffers.ByteBuffer, obj?:PeerConnectionId):PeerConnectionId {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PeerConnectionId()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

updatedAt():string|null
updatedAt(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
updatedAt(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startPeerConnectionId(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addUpdatedAt(builder:flatbuffers.Builder, updatedAtOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, updatedAtOffset, 0);
}

static endPeerConnectionId(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishPeerConnectionIdBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedPeerConnectionIdBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createPeerConnectionId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, updatedAtOffset:flatbuffers.Offset):flatbuffers.Offset {
  PeerConnectionId.startPeerConnectionId(builder);
  PeerConnectionId.addId(builder, idOffset);
  PeerConnectionId.addUpdatedAt(builder, updatedAtOffset);
  return PeerConnectionId.endPeerConnectionId(builder);
}
}
