// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum Reason {
  Other = 0,
  Generate = 1,
  Imported = 2,
  Draw = 3,
  Mask = 4,
  Scribble = 5,
  Moodboard = 6,
  DepthMap = 7,
  Clear = 8
}
