// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class ScriptSession {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ScriptSession {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsScriptSession(bb:flatbuffers.ByteBuffer, obj?:ScriptSession):ScriptSession {
  return (obj || new ScriptSession()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsScriptSession(bb:flatbuffers.ByteBuffer, obj?:ScriptSession):ScriptSession {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ScriptSession()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

executionGroupId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

file():string|null
file(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
file(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

models(index: number):string
models(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
models(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

modelsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

loras(index: number):string
loras(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
loras(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

lorasLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

controls(index: number):string
controls(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
controls(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

controlsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startScriptSession(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addId(builder:flatbuffers.Builder, id:bigint) {
  builder.addFieldInt64(0, id, BigInt('0'));
}

static addExecutionGroupId(builder:flatbuffers.Builder, executionGroupId:bigint) {
  builder.addFieldInt64(1, executionGroupId, BigInt('0'));
}

static addFile(builder:flatbuffers.Builder, fileOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, fileOffset, 0);
}

static addModels(builder:flatbuffers.Builder, modelsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, modelsOffset, 0);
}

static createModelsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startModelsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addLoras(builder:flatbuffers.Builder, lorasOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, lorasOffset, 0);
}

static createLorasVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startLorasVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addControls(builder:flatbuffers.Builder, controlsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, controlsOffset, 0);
}

static createControlsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startControlsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endScriptSession(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishScriptSessionBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedScriptSessionBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createScriptSession(builder:flatbuffers.Builder, id:bigint, executionGroupId:bigint, fileOffset:flatbuffers.Offset, modelsOffset:flatbuffers.Offset, lorasOffset:flatbuffers.Offset, controlsOffset:flatbuffers.Offset):flatbuffers.Offset {
  ScriptSession.startScriptSession(builder);
  ScriptSession.addId(builder, id);
  ScriptSession.addExecutionGroupId(builder, executionGroupId);
  ScriptSession.addFile(builder, fileOffset);
  ScriptSession.addModels(builder, modelsOffset);
  ScriptSession.addLoras(builder, lorasOffset);
  ScriptSession.addControls(builder, controlsOffset);
  return ScriptSession.endScriptSession(builder);
}
}
