// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum SeedMode {
  Legacy = 0,
  TorchCpuCompatible = 1,
  ScaleAlike = 2,
  NvidiaGpuCompatible = 3
}
