// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class TensorData {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TensorData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTensorData(bb:flatbuffers.ByteBuffer, obj?:TensorData):TensorData {
  return (obj || new TensorData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTensorData(bb:flatbuffers.ByteBuffer, obj?:TensorData):TensorData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TensorData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

lineage():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

logicalTime():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

index():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

x():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

y():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

width():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

height():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

scaleFactorBy120():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

tensorId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

maskId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

depthMapId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

scribbleId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

poseId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

colorPaletteId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

customId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startTensorData(builder:flatbuffers.Builder) {
  builder.startObject(15);
}

static addLineage(builder:flatbuffers.Builder, lineage:bigint) {
  builder.addFieldInt64(0, lineage, BigInt('0'));
}

static addLogicalTime(builder:flatbuffers.Builder, logicalTime:bigint) {
  builder.addFieldInt64(1, logicalTime, BigInt('0'));
}

static addIndex(builder:flatbuffers.Builder, index:bigint) {
  builder.addFieldInt64(2, index, BigInt('0'));
}

static addX(builder:flatbuffers.Builder, x:number) {
  builder.addFieldInt32(3, x, 0);
}

static addY(builder:flatbuffers.Builder, y:number) {
  builder.addFieldInt32(4, y, 0);
}

static addWidth(builder:flatbuffers.Builder, width:number) {
  builder.addFieldInt32(5, width, 0);
}

static addHeight(builder:flatbuffers.Builder, height:number) {
  builder.addFieldInt32(6, height, 0);
}

static addScaleFactorBy120(builder:flatbuffers.Builder, scaleFactorBy120:number) {
  builder.addFieldInt32(7, scaleFactorBy120, 0);
}

static addTensorId(builder:flatbuffers.Builder, tensorId:bigint) {
  builder.addFieldInt64(8, tensorId, BigInt('0'));
}

static addMaskId(builder:flatbuffers.Builder, maskId:bigint) {
  builder.addFieldInt64(9, maskId, BigInt('0'));
}

static addDepthMapId(builder:flatbuffers.Builder, depthMapId:bigint) {
  builder.addFieldInt64(10, depthMapId, BigInt('0'));
}

static addScribbleId(builder:flatbuffers.Builder, scribbleId:bigint) {
  builder.addFieldInt64(11, scribbleId, BigInt('0'));
}

static addPoseId(builder:flatbuffers.Builder, poseId:bigint) {
  builder.addFieldInt64(12, poseId, BigInt('0'));
}

static addColorPaletteId(builder:flatbuffers.Builder, colorPaletteId:bigint) {
  builder.addFieldInt64(13, colorPaletteId, BigInt('0'));
}

static addCustomId(builder:flatbuffers.Builder, customId:bigint) {
  builder.addFieldInt64(14, customId, BigInt('0'));
}

static endTensorData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishTensorDataBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedTensorDataBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createTensorData(builder:flatbuffers.Builder, lineage:bigint, logicalTime:bigint, index:bigint, x:number, y:number, width:number, height:number, scaleFactorBy120:number, tensorId:bigint, maskId:bigint, depthMapId:bigint, scribbleId:bigint, poseId:bigint, colorPaletteId:bigint, customId:bigint):flatbuffers.Offset {
  TensorData.startTensorData(builder);
  TensorData.addLineage(builder, lineage);
  TensorData.addLogicalTime(builder, logicalTime);
  TensorData.addIndex(builder, index);
  TensorData.addX(builder, x);
  TensorData.addY(builder, y);
  TensorData.addWidth(builder, width);
  TensorData.addHeight(builder, height);
  TensorData.addScaleFactorBy120(builder, scaleFactorBy120);
  TensorData.addTensorId(builder, tensorId);
  TensorData.addMaskId(builder, maskId);
  TensorData.addDepthMapId(builder, depthMapId);
  TensorData.addScribbleId(builder, scribbleId);
  TensorData.addPoseId(builder, poseId);
  TensorData.addColorPaletteId(builder, colorPaletteId);
  TensorData.addCustomId(builder, customId);
  return TensorData.endTensorData(builder);
}
}
