// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class TensorMoodboardData {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TensorMoodboardData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTensorMoodboardData(bb:flatbuffers.ByteBuffer, obj?:TensorMoodboardData):TensorMoodboardData {
  return (obj || new TensorMoodboardData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTensorMoodboardData(bb:flatbuffers.ByteBuffer, obj?:TensorMoodboardData):TensorMoodboardData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TensorMoodboardData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

lineage():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

logicalTime():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

index():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

shuffleId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

weight():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startTensorMoodboardData(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addLineage(builder:flatbuffers.Builder, lineage:bigint) {
  builder.addFieldInt64(0, lineage, BigInt('0'));
}

static addLogicalTime(builder:flatbuffers.Builder, logicalTime:bigint) {
  builder.addFieldInt64(1, logicalTime, BigInt('0'));
}

static addIndex(builder:flatbuffers.Builder, index:bigint) {
  builder.addFieldInt64(2, index, BigInt('0'));
}

static addShuffleId(builder:flatbuffers.Builder, shuffleId:bigint) {
  builder.addFieldInt64(3, shuffleId, BigInt('0'));
}

static addWeight(builder:flatbuffers.Builder, weight:number) {
  builder.addFieldFloat32(4, weight, 0.0);
}

static endTensorMoodboardData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishTensorMoodboardDataBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedTensorMoodboardDataBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createTensorMoodboardData(builder:flatbuffers.Builder, lineage:bigint, logicalTime:bigint, index:bigint, shuffleId:bigint, weight:number):flatbuffers.Offset {
  TensorMoodboardData.startTensorMoodboardData(builder);
  TensorMoodboardData.addLineage(builder, lineage);
  TensorMoodboardData.addLogicalTime(builder, logicalTime);
  TensorMoodboardData.addIndex(builder, index);
  TensorMoodboardData.addShuffleId(builder, shuffleId);
  TensorMoodboardData.addWeight(builder, weight);
  return TensorMoodboardData.endTensorMoodboardData(builder);
}
}
