// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { TextRange } from './text-range.js';
import { TextType } from './text-type.js';


export class TextModification {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TextModification {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTextModification(bb:flatbuffers.ByteBuffer, obj?:TextModification):TextModification {
  return (obj || new TextModification()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTextModification(bb:flatbuffers.ByteBuffer, obj?:TextModification):TextModification {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TextModification()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

type():TextType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : TextType.PositiveText;
}

range(obj?:TextRange):TextRange|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new TextRange()).__init(this.bb_pos + offset, this.bb!) : null;
}

text():string|null
text(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
text(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startTextModification(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addType(builder:flatbuffers.Builder, type:TextType) {
  builder.addFieldInt8(0, type, TextType.PositiveText);
}

static addRange(builder:flatbuffers.Builder, rangeOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, rangeOffset, 0);
}

static addText(builder:flatbuffers.Builder, textOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, textOffset, 0);
}

static endTextModification(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
