// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { TextModification } from './text-modification.js';


export class TextHistoryNode {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TextHistoryNode {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTextHistoryNode(bb:flatbuffers.ByteBuffer, obj?:TextHistoryNode):TextHistoryNode {
  return (obj || new TextHistoryNode()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTextHistoryNode(bb:flatbuffers.ByteBuffer, obj?:TextHistoryNode):TextHistoryNode {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TextHistoryNode()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

lineage():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

logicalTime():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

startEdits():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

startPositiveText():string|null
startPositiveText(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
startPositiveText(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

startNegativeText():string|null
startNegativeText(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
startNegativeText(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

modifications(index: number, obj?:TextModification):TextModification|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new TextModification()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

modificationsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startTextHistoryNode(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addLineage(builder:flatbuffers.Builder, lineage:bigint) {
  builder.addFieldInt64(0, lineage, BigInt('0'));
}

static addLogicalTime(builder:flatbuffers.Builder, logicalTime:bigint) {
  builder.addFieldInt64(1, logicalTime, BigInt('0'));
}

static addStartEdits(builder:flatbuffers.Builder, startEdits:bigint) {
  builder.addFieldInt64(2, startEdits, BigInt('0'));
}

static addStartPositiveText(builder:flatbuffers.Builder, startPositiveTextOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, startPositiveTextOffset, 0);
}

static addStartNegativeText(builder:flatbuffers.Builder, startNegativeTextOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, startNegativeTextOffset, 0);
}

static addModifications(builder:flatbuffers.Builder, modificationsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, modificationsOffset, 0);
}

static createModificationsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startModificationsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endTextHistoryNode(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishTextHistoryNodeBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedTextHistoryNodeBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createTextHistoryNode(builder:flatbuffers.Builder, lineage:bigint, logicalTime:bigint, startEdits:bigint, startPositiveTextOffset:flatbuffers.Offset, startNegativeTextOffset:flatbuffers.Offset, modificationsOffset:flatbuffers.Offset):flatbuffers.Offset {
  TextHistoryNode.startTextHistoryNode(builder);
  TextHistoryNode.addLineage(builder, lineage);
  TextHistoryNode.addLogicalTime(builder, logicalTime);
  TextHistoryNode.addStartEdits(builder, startEdits);
  TextHistoryNode.addStartPositiveText(builder, startPositiveTextOffset);
  TextHistoryNode.addStartNegativeText(builder, startNegativeTextOffset);
  TextHistoryNode.addModifications(builder, modificationsOffset);
  return TextHistoryNode.endTextHistoryNode(builder);
}
}
