// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class TextRange {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TextRange {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

location():number {
  return this.bb!.readInt32(this.bb_pos);
}

length():number {
  return this.bb!.readInt32(this.bb_pos + 4);
}

static sizeOf():number {
  return 8;
}

static createTextRange(builder:flatbuffers.Builder, location: number, length: number):flatbuffers.Offset {
  builder.prep(4, 8);
  builder.writeInt32(length);
  builder.writeInt32(location);
  return builder.offset();
}

}
