// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class TextLineageNode {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TextLineageNode {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTextLineageNode(bb:flatbuffers.ByteBuffer, obj?:TextLineageNode):TextLineageNode {
  return (obj || new TextLineageNode()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTextLineageNode(bb:flatbuffers.ByteBuffer, obj?:TextLineageNode):TextLineageNode {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TextLineageNode()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

lineage():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

pointTo():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startTextLineageNode(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addLineage(builder:flatbuffers.Builder, lineage:bigint) {
  builder.addFieldInt64(0, lineage, BigInt('0'));
}

static addPointTo(builder:flatbuffers.Builder, pointTo:bigint) {
  builder.addFieldInt64(1, pointTo, BigInt('0'));
}

static endTextLineageNode(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishTextLineageNodeBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedTextLineageNodeBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createTextLineageNode(builder:flatbuffers.Builder, lineage:bigint, pointTo:bigint):flatbuffers.Offset {
  TextLineageNode.startTextLineageNode(builder);
  TextLineageNode.addLineage(builder, lineage);
  TextLineageNode.addPointTo(builder, pointTo);
  return TextLineageNode.endTextLineageNode(builder);
}
}
