// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class TrainingData {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TrainingData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTrainingData(bb:flatbuffers.ByteBuffer, obj?:TrainingData):TrainingData {
  return (obj || new TrainingData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTrainingData(bb:flatbuffers.ByteBuffer, obj?:TrainingData):TrainingData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TrainingData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

caption():string|null
caption(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
caption(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startTrainingData(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addCaption(builder:flatbuffers.Builder, captionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, captionOffset, 0);
}

static endTrainingData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishTrainingDataBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedTrainingDataBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createTrainingData(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, captionOffset:flatbuffers.Offset):flatbuffers.Offset {
  TrainingData.startTrainingData(builder);
  TrainingData.addId(builder, idOffset);
  TrainingData.addCaption(builder, captionOffset);
  return TrainingData.endTrainingData(builder);
}
}
